# Generated by Django 3.2.3 on 2021-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
